apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account-ilender
  namespace: ilender-tekton-ocp-ns
secrets:
  - name: secret-git-ilender
  - name: secret-docker-ilender
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-ilender-tekton-ocp-ns
  namespace: ilender-tekton-ocp-ns
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: service-account-ilender
  namespace: ilender-tekton-ocp-ns
---
### If you are not creating this ClusterRoleBinding, you need to run the below command....
### oc policy add-role-to-user edit system:serviceaccount:ilender-tekton-ocp-ns:pipeline -n ilender-tekton-ocp-ns
