apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: secret-git-ilender
  namespace: ilender-tekton-ocp-ns
  annotations:
    tekton.dev/git-0: https://github.ibm.com
  labels:
    serviceAccount: service-account-ilender
    serviceAccountName: service-account-ilender
stringData:
  password: 30c4d3cd829dbb9496f01bc7caf64c34bd291065
  username: jeyagandhi
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: secret-docker-ilender
  namespace: ilender-tekton-ocp-ns
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
  labels:
    serviceAccount: service-account-ilender
    serviceAccountName: service-account-ilender
stringData:
  password: f2924403-2196-4430-b168-3f5bad8ef0ab
  username: gandigit
---
# kubectl create secret docker-registry my-secret --docker-server=DOCKER_REGISTRY_SERVER --docker-username=DOCKER_USER --docker-password=DOCKER_PASSWORD --docker-email=DOCKER_EMAIL --dry-run -o yaml
# oc create secret docker-registry secret-ibm-container-jp2-registry-ilender --docker-username=iamapikey --docker-password=dIIjsNeAbyGVxhVldyMjkCAVWnTx4aTbFmYBLvS04u02 --docker-email=user@ibm.com --docker-server=jp.icr.io -n ilender-tekton-ocp-ns --dry-run -o yaml
