apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-deploy
  namespace: ilender-tekton-ocp-ns
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
  params:
    - name: pathToDeploymentFiles
      description: Path to deployment yaml files
      # default: /workspace/source-repo/deployment/01-ocp/yaml/
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source-repo
      command: ['/bin/bash', '-c']
      args:
      - |-
        oc apply -f $(inputs.params.pathToDeploymentFiles)
